# Generated by Django 6.0.4 on 2026-04-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('member', 'Miembro')], max_length=30),
        ),
    ]
